---
- hosts: main
  become: true

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Ensure apt cache is updated.
      apt: update_cache=true cache_valid_time=600

  roles:
    - geerlingguy.firewall
    - geerlingguy.docker
